name: "${project.name}"
main: "${project.groupId}.Pl3xMapGriefdefender"
version: "${project.version}"
description: "${project.description}"
api-version: "1.16"
authors: [ BillyGalbreath , ahdg ]
softdepend:
  - GriefDefender
  - Pl3xMap
